server:
  port: '8090'

eureka:
  instance:
    preferIpAddress: 'false'
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8083/eureka}

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: customer 
          uri: lb://customer-service
          predicates:
            - Path=/api/customer-service/**
        - id: product 
          uri: lb://product-service
          predicates:
            - Path=/api/product-service/**
